### ISSUE TITLE
Looks like deps have changed and cause ruby_bosh to break

### ISSUE THREAD

**Issue by glongman** [skyfallsin/ruby_bosh#1]
what version of adamwiggins-rest-client does your gem require?

Thanks. Geoff

My observation and environment:

```
geoff:~ glongman$ gem list | grep bosh
skyfallsin-ruby_bosh (0.5.4)

geoff:~ glongman$ irb
>> require 'rubygems'
=> false
>> require 'ruby_bosh'
LoadError: no such file to load -- /Library/Ruby/Gems/1.8/gems/adamwiggins-rest-client-1.0/lib/restclient/mixin/response
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
from /Library/Ruby/Gems/1.8/gems/adamwiggins-rest-client-1.0/lib/restclient.rb:7
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
from /Library/Ruby/Gems/1.8/gems/adamwiggins-rest-client-1.0/lib/rest_client.rb:2
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `require'
from /Library/Ruby/Gems/1.8/gems/skyfallsin-ruby_bosh-0.5.4/lib/ruby_bosh.rb:1
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:36:in `require'
from (irb):2
>>
```

installed dep list: 
    builder (2.1.2)
    adamwiggins-rest-client (1.0)
    hpricot (0.6)
    SystemTimer (1.1.1)

my env (Mac OSX 10.5.6):
    ruby 1.8.6.114
    rubygems 1.3.1

**Comment by glongman** [comment]
Well it appears that adamwiggins' gem is broken. 1.0 appeared yesterday.

sorry for the bother. I will add an issue over there.

Geoff
